config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :transactions do
    collection do
      get 'missing'
      get 'report'
      get 'report/detail', action: 'report_detail'
      post 'dismiss'
    end
  end
  resources :categories

  root :to => redirect("/users/sign_in")
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

  scope :debits_first, -> {order(category_type: :desc, group: :asc, description: :asc)}
  scope :from_group, -> (group_name) {where("`group` = ?", group_name)}

  validates_presence_of :description, :group, :category_type, :frequency
  validate :only_debits_can_be_investment

  def only_debits_can_be_investment
    if investment?
      errors.add(:base, 'Only debits can be marked as an investment') unless debit?
    end
  end

  def full_description
    "#{group}/#{description}"
  end

  def debit?
    category_type.to_sym == :debit
  end

  def credit?
    !debit?
  end

  def monthly?
    frequency.to_sym == :monthly
  end

  def weekly?
    frequency.to_sym == :weekly
  end

  def daily?
    frequency.to_sym == :daily
  end

  def oftenly?
    frequency.to_sym == :oftenly
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = current_user.categories.debits_first.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @category.user = current_user
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category_type, :description, :group, :value, :frequency, :disabled, :investment)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_type %><br>
    <%= f.select :category_type, [['Debit', :debit], ['Credit', :credit]] %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :frequency %><br>
    <%= f.select :frequency, [['Occasionally', :occasionally], ['Monthly', :monthly], ['Weekly', :weekly], ['Daily', :daily]] %>
  </div>
  <div class="field">
    <%= f.label :investment %><br>
    <%= f.check_box :investment %>
  </div>
  <div class="field">
    <%= f.label :disabled %><br>
    <%= f.check_box :disabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<p>
  <%= link_to 'New Category', new_category_path %> |
  <%= link_to 'Transactions', transactions_path %>
</p>

<table class="categorias">
  <thead>
    <tr>
      <th>Type</th>
      <th>Group</th>
      <th>Description</th>
      <th>Frequency</th>
      <th>Disabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <%@grouped_categories = @categories.group_by(&:group)%>
  <%@grouped_categories.each do |group, categories_of_group|%>
    <tbody>
    <%first = true%>
    <%categories_of_group.each do |category| %>
      <tr class="<%=category.category_type%>">
        <td><%= category.category_type.humanize %></td>
        <td><%= category.group if first%></td>
        <td><%= category.description %></td>
        <td><%= category.frequency.humanize %></td>
        <td><%= category.disabled %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <%first = false%>
    <% end %>
    </tbody>
  <% end %>
</table>

<br>

<%= link_to 'New Category', new_category_path %> |
<%= link_to 'Transactions', transactions_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @category.category_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Group:</strong>
  <%= @category.group %>
</p>

<p>
  <strong>Frequency:</strong>
  <%= @category.frequency %>
</p>

<p>
  <strong>Investment:</strong>
  <%= @category.investment %>
</p>

<p>
  <strong>Disabled:</strong>
  <%= @category.disabled %>
</p>

<%= link_to 'New Category', new_category_path %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %> |
<%= link_to 'New Transaction', new_transaction_path %>