config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :transactions do
    collection do
      get 'missing'
      get 'report'
      get 'report/detail', action: 'report_detail'
      post 'dismiss'
    end
  end
  resources :categories

  root :to => redirect("/users/sign_in")
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include DateHelper
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]


  def index
    date_ranges = date_range(params)
    @transactions = current_user.transactions
      .since(date_ranges.first)
      .until(date_ranges.last)
      .oldest_first
      .all
    @credits_count = @transactions.count{|t| t.category.credit?}
    @credits_total = @transactions.select{|t| t.category.credit?}.inject(0) {|sum, t| sum + t.amount}

    @debits_count = @transactions.count{|t| t.category.debit?}
    @debits_total = @transactions.select{|t| t.category.debit?}.inject(0) {|sum, t| sum + t.amount}

    @current_balance = @transactions.balance
  end

  def show
  end

  def new
    @transaction = Transaction.new
    @transaction.date = Time.now
    @categories = current_user.categories.debits_first
  end

  def edit
    @categories = current_user.categories.debits_first
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user
    creating_missing = "true" == params["missing_transactions_flag"]

    respond_to do |format|
      #if @transaction.save
      if TransactionService.save(@transaction)
        format.html {
          if creating_missing
            redirect_to missing_transactions_path, notice: 'Transaction was successfully created.' 
          else
            redirect_to @transaction, notice: 'Transaction was successfully created.' 
          end
        }
        format.json { render :show, status: :created, location: @transaction }
      else
        @categories = current_user.categories.debits_first
        format.html { 
          if creating_missing
            redirect_to missing_transactions_path, flash: {error: @transaction.errors.full_messages}
          else
            render :new
          end
        }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @transaction.user = current_user
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        @categories = current_user.categories.debits_first
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    #@transaction.destroy
    TransactionService.destroy(@transaction)
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def missing
    date_ranges = date_range(params)
    @missing_transactions = TransactionService.compute_missing_transactions_for_date(current_user, date_ranges.first.to_datetime.to_date..date_ranges.last.to_datetime.to_date)
    @transaction = Transaction.new
    @transaction.date = Time.now
    @categories = current_user.categories.debits_first
  end

  def report

    #extract to service

    @existing_params = params.to_unsafe_h.slice("year", "month")

    date_ranges = date_range(params)
    previous_date_range = previous_date_range(date_ranges)
    @transactions = current_user.transactions
      .since(date_ranges.first)
      .until(date_ranges.last)
      .oldest_first
      .all

    @previous_transactions = current_user.transactions
      .since(previous_date_range.first)
      .until(previous_date_range.last)
      .oldest_first
      .all

    @report = {}
    @report[:debit] = Hash[@transactions.select{|t| t.debit?}.group_by{|t| t.category.group}.sort_by{|k,v| v.sum(&:amount)}]
    @report[:credit] = Hash[@transactions.select{|t| t.credit?}.group_by{|t| t.category.group}.sort_by{|k, v| v.sum(&:amount)}.reverse]

    @debits_total = @report[:debit].values.flat_map{|a| a}.sum{|t| t.amount}
    @credits_total = @report[:credit].values.flat_map{|a| a}.sum{|t| t.amount}

    @current_balance = @transactions.balance

    @investments_total = @transactions.select{|t| t.category.investment?}.sum{|t| t.amount}

    @previous_report = {}
    @previous_report[:debit] = Hash[@previous_transactions.select{|t| t.debit?}.group_by{|t| t.category.group}.sort_by{|k,v| v.sum(&:amount)}]
    @previous_report[:credit] = Hash[@previous_transactions.select{|t| t.credit?}.group_by{|t| t.category.group}.sort_by{|k, v| v.sum(&:amount)}.reverse]

    @previous_debits_total = @previous_report[:debit].values.flat_map{|a| a}.sum{|t| t.amount} * 1.0
    @previous_credits_total = @previous_report[:credit].values.flat_map{|a| a}.sum{|t| t.amount} * 1.0

    @previous_balance = @previous_transactions.balance
    @previous_investments_total = @previous_transactions.select{|t| t.category.investment?}.sum{|t| t.amount}


  end

  def report_detail
    @existing_params = params.to_unsafe_h.slice("year", "month")

    date_ranges = date_range(params)
    @transactions = current_user.transactions
      .since(date_ranges.first)
      .until(date_ranges.last)
      .from_group(params[:group_name])

    @current_balance = @transactions.balance
    @transactions_count = @transactions.size
  end

  def dismiss
    TransactionService.dismiss(dismiss_params[:missing_hash], current_user)
    redirect_to missing_transactions_path, notice: 'Suggestion was successfully dismissed.' 
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def transaction_params
      params.require(:transaction).permit(:date, :amount, :category_id, :payee, :installments)
    end

    def dismiss_params
      params.require(:dismiss_hash).permit(:missing_hash)
    end    

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if local_assigns[:missing_transactions_flag] %>
    <%= hidden_field_tag :missing_transactions_flag, "true"%>
  <%end%>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, @categories.collect{|c| ["#{c.full_description} - #{c.category_type}", c.id]} %>
    <%= link_to 'New Category', new_category_path %>
  </div>
  <div class="field">
    <%= f.label :payee %><br>
    <%= f.text_field :payee %>
  </div>
  <%unless @transaction.id%>
    <div class="field">
      <%= f.label :installments %><br>
      <%= f.text_field :installments %>
    </div>
  <%end%>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions</h1>

<p>
  <%= link_to 'New Transaction', new_transaction_path %> |
  <%= link_to 'Categories', categories_path %> |
  <%= get_month_link('Missing Transactions', missing_transactions_path) %> |
  <%= get_month_link('Report', report_transactions_path) %> |
  <%= previous_month_link(transactions_path) %> | 
  <%= next_month_link(transactions_path) %>
</p>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Category</th>
      <th>Payee</th>
      <th>Installment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr class="<%=transaction.category.category_type%>">
        <td><%= transaction.date %></td>
        <td class="currency"><%= number_to_currency(transaction.normalized_amount, unit: "") %></td>
        <td><%= transaction.category.full_description %></td>
        <td><%= transaction.payee %></td>
        <td>
          <%if transaction.installment_plan? %>
            <%= transaction.installment_number%>/<%=transaction.installments %>
          <%end%>
        </td>
        <td><%= link_to 'Show', transaction %></td>
        <td>
          <%unless transaction.installment_plan? %>
            <%= link_to 'Edit', edit_transaction_path(transaction) %></td>
          <%end%>
        <td>
          <%if transaction.installment_plan_child? %>
            <%= link_to 'View Parent', transaction_path(transaction.installment_transaction.id) %></td>
          <% else %>
            <%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>Créditos: <%=@credits_count%></td>
      <td class="currency"><%=number_to_currency(@credits_total, unit:"")%></td>
    </tr>
    <tr>
      <td>Débitos: <%=@debits_count%></td>
      <td class="currency"><%=number_to_currency(@debits_total, unit:"")%></td>
    </tr>
    <tr>
      <td colspan="2" class="currency"><%=number_to_currency(@current_balance, unit:"")%></td>
    </tr>
  </tfoot>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %> |
<%= link_to 'Categories', categories_path %> |
<%= get_month_link('Missing Transactions', missing_transactions_path) %> |
<%= get_month_link('Report', report_transactions_path) %> |
<%= previous_month_link(transactions_path) %> | 
<%= next_month_link(transactions_path) %>

app/views/transactions/missing.html.erb
<p id="notice"><%= notice %></p>

<h1>Missing Transactions</h1>
<% if flash[:error] && flash[:error].any? %>
  <div id="error_explanation">
    <h2><%= pluralize(flash[:error].count, "error") %> prohibited this transaction from being saved:</h2>

    <ul>
    <% flash[:error].each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= link_to 'Categories', categories_path %> |  
  <%= get_month_link('Transactions', transactions_path) %> |
  <%= get_month_link('Report', report_transactions_path) %> |
  <%= previous_month_link(missing_transactions_path) %> | 
  <%= next_month_link(missing_transactions_path) %>
</p>

<% @missing_transactions.each do |frequency, transactions| %>
  <%if !@missing_transactions[frequency].empty? %>
    <h2>
      <%if frequency == :daily%>
        Daily
      <%elsif frequency == :weekly%>
        Weekly
      <%else%>
        Monthly
      <%end%>
    </h2>
    <table>
      <thead>
        <tr>
          <th>Category</th>
          <th>Date</th>
          <th>Amount</th>
          <th>Payee</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% transactions.each do |transaction| %>
            
              <tr class="<%=transaction.category.category_type%>">
                <%= form_for(transaction) do |f| %>
                  <td>
                    <%= transaction.category.full_description %>
                    <%= f.hidden_field :category_id, value: transaction.category.id%>
                    <%= hidden_field_tag :missing_transactions_flag, "true"%>
                  </td>
                  <td><%= f.date_select :date %><%=transaction.date.strftime('%a')%></td>
                  <td class="currency"><%= f.text_field :amount %></td>
                  <!--<= number_to_currency(transaction.normalized_amount, unit: "") >-->
                  <td>
                    <%= f.text_field :payee %>
                    <%= f.submit "Go!"%>
                  </td>
                <%end%>
                <%= form_for :dismiss_hash, url: dismiss_transactions_path do |f| %>
                  <td>
                    <%= f.hidden_field :missing_hash, value: transaction.missing_hash%>
                    <%= f.submit "Dismiss"%>
                  </td>
                <%end%>
              </tr>
            
        <% end %>
        <%= transactions.size %>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="2" class="currency"><%=number_to_currency(@current_balance, unit:"")%></td>
        </tr>
      </tfoot>
    </table>
  <%end%>
<%end%>
<% if @missing_transactions.values.flatten.empty? %>
    <p>No missing transactions</p>
<%end%>
<h1>New Transaction</h1>
<%= render partial: 'form', locals: {missing_transactions_flag: true} %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/report.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions Report</h1>
<p>
  <%= link_to 'Categories', categories_path %> |
  <%= get_month_link('Transactions', transactions_path) %> |
  <%= get_month_link('Missing Transactions', missing_transactions_path) %> |  
  <%= previous_month_link(report_transactions_path) %> | 
  <%= next_month_link(report_transactions_path) %>
</p>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Total</th>
      <th>%</th>
      <th>&Delta;p.p</th>
      <th>&Delta;% - Category</th>
      <th>&Delta;$</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @report.each do |category_type, groups| %>
    <tbody>
      <% groups.each do |group, transactions| %>
        <tr class="<%=category_type%>">
          <td><%=link_to group, report_detail_transactions_path({group_name: group}.merge(@existing_params))%></td>
          <td class="currency"><%= number_to_currency(transactions.sum{|t| t.amount}, unit: "") %></td>
          <%
            percentile = (transactions.sum{|t| t.amount}.abs / @credits_total) * 100
            previous_transactions_of_group = @previous_report[category_type][group] || []
            previous_percentile = (previous_transactions_of_group.sum{|t| t.amount}.abs / @previous_credits_total) * 100

            percentile = 0 if percentile.infinite?
            previous_percentile = 0 if previous_percentile.infinite? || previous_percentile.nan?

            percentile_delta = (previous_percentile != 0.0) ? (percentile - previous_percentile) : 0
            percentile_delta_relative = (previous_percentile != 0.0) ? ((percentile / (previous_percentile) - 1) * 100) : 0

            amount = (transactions.sum{|t| t.amount}.abs)
            previous_amount = (previous_transactions_of_group.sum{|t| t.amount}.abs)
            amount_delta = amount - previous_amount
          %>
          <td class="currency"><%=number_to_currency(percentile, unit:"")%></td>
          <td class="currency"><%=number_to_currency(percentile_delta, unit:"")%></td>
          <td class="currency">
            <%=number_to_currency(percentile_delta_relative, unit:"")%>
          </td>
          <td class="currency"><%=number_to_currency(amount_delta, unit:"")%></td>
        </tr>
      <% end %>
    </tbody>
  <%end%>
  <tfoot>
    <tr>
      <td>Total Créditos</td>
      <td class="currency"><%=number_to_currency(@credits_total, unit:"")%></td>
      <td class="currency">&nbsp;</td>
      <td class="currency">&nbsp;</td>
      <td class="currency">
        <%
          previous_amount = @previous_credits_total
          amount = @credits_total
          amount_delta = previous_amount != 0 ? ((amount / previous_amount) - 1) * 100 : 0
        %>
        <%=number_to_currency(amount_delta, unit:"")%>
      </td>
      <td class="currency"><%=number_to_currency(@credits_total - @previous_credits_total, unit:"")%></td>
    </tr>
    <tr>
      <td>Total Débitos</td>
      <td class="currency"><%=number_to_currency(@debits_total, unit:"")%></td>
      <td class="currency">&nbsp;</td>
      <td class="currency">&nbsp;</td>
      <td class="currency">
        <%
          previous_amount = @previous_debits_total
          amount = @debits_total
          amount_delta = previous_amount != 0 ? ((amount / previous_amount) - 1) * 100 : 0
        %>
        <%=number_to_currency(amount_delta, unit:"")%>
      </td>
      <td class="currency"><%=number_to_currency((@debits_total - @previous_debits_total) * -1, unit:"")%></td>
    </tr>
    <tr>
      <td>Saldo</td>
      <td class="currency"><%=number_to_currency(@current_balance, unit:"")%></td>
      <td class="currency">&nbsp;</td>
      <td class="currency">&nbsp;</td>
      <td class="currency">
        <%
          previous_amount = @previous_balance
          amount = @current_balance
          amount_delta = previous_amount != 0 ? ((amount / previous_amount) - 1) * 100 : 0
        %>
        <%=number_to_currency(amount_delta, unit:"")%>
      </td>
      <td class="currency"><%=number_to_currency((@current_balance - @previous_balance), unit:"")%></td>
    </tr>
    <tr>
      <td>Investimentos</td>
      <td class="currency"><%=number_to_currency(@investments_total, unit:"")%></td>
      <td class="currency">&nbsp;</td>
      <td class="currency">&nbsp;</td>
      <td class="currency">
        <%
          previous_amount = @previous_investments_total
          amount = @investments_total
          amount_delta = previous_amount != 0 ? ((amount / previous_amount) - 1) * 100 : 0
        %>
        <%=number_to_currency(amount_delta, unit:"")%>
      </td>
      <td class="currency"><%=number_to_currency((@investments_total - @previous_investments_total) * -1, unit:"")%></td>
    </tr>
    <tr>
      <td>Total Gastos</td>
      <td class="currency"><%=number_to_currency(@debits_total - @investments_total, unit:"")%></td>
      <td class="currency">&nbsp;</td>
      <td class="currency">&nbsp;</td>
      <td class="currency">
        <%
          previous_amount = (@previous_debits_total - @previous_investments_total)
          amount = (@debits_total - @investments_total)
          amount_delta = previous_amount != 0 ? ((amount / previous_amount) - 1) * 100 : 0
        %>
        <%=number_to_currency(amount_delta, unit:"")%>
      </td>
      <td class="currency"><%=number_to_currency(((@debits_total - @investments_total) * -1) - ((@previous_debits_total - @previous_investments_total) * -1), unit:"")%></td>
    </tr>
  </tfoot>
</table>

app/views/transactions/report_detail.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transactions for group <%=params[:group_name]%></h1>

<p>
  <%= link_to 'Voltar', report_transactions_path(@existing_params) %>
</p>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
      <th>Category</th>
      <th>Payee</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr class="<%=transaction.category.category_type%>">
        <td><%= transaction.date %></td>
        <td class="currency"><%= number_to_currency(transaction.normalized_amount, unit: "") %></td>
        <td><%= transaction.category.full_description %></td>
        <td><%= transaction.payee %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td>Transações: <%=@transactions_count%></td>
      <td class="currency"><%=number_to_currency(@current_balance, unit:"")%></td>
    </tr>
  </tfoot>
</table>

<br>

<%= link_to 'Voltar', report_transactions_path(@existing_params) %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.normalized_amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @transaction.category.full_description %>
</p>

<p>
  <strong>Payee:</strong>
  <%= @transaction.payee %>
</p>

<p>
  <strong>Installments:</strong>
  <%= @transaction.installment_number%>/<%=@transaction.installments %>
</p>

<%if @transaction.installment_plan_child?%>
  <p>
    <strong>Source:</strong>
    <%= link_to "View source transaction", transaction_path(@transaction.installment_transaction.id)%>
  </p>
<%end%>

<%= link_to 'New Transaction', new_transaction_path %> |
<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>